from __future__ import annotations

from dataclasses import dataclass

from app.connectors.base import ConnectorDefinition


@dataclass(frozen=True)
class ConnectorRegistry:
    connectors: tuple[ConnectorDefinition, ...]

    def list_definitions(self) -> list[ConnectorDefinition]:
        return list(self.connectors)

    def get(self, key: str) -> ConnectorDefinition | None:
        for connector in self.connectors:
            if connector.key == key:
                return connector
        return None


def _connector(
    *,
    key: str,
    display_name: str,
    layer: str,
    admin_status: str,
    rollout_stage: str,
    pagination_mode: str,
    supports_incremental_sync: bool,
    rate_limit_per_minute: int,
) -> ConnectorDefinition:
    return ConnectorDefinition(
        key=key,
        display_name=display_name,
        layer=layer,  # type: ignore[arg-type]
        admin_status=admin_status,  # type: ignore[arg-type]
        rollout_stage=rollout_stage,  # type: ignore[arg-type]
        pagination_mode=pagination_mode,  # type: ignore[arg-type]
        supports_incremental_sync=supports_incremental_sync,
        rate_limit_per_minute=rate_limit_per_minute,
    )


def build_default_registry() -> ConnectorRegistry:
    return ConnectorRegistry(
        connectors=(
            _connector(
                key="greenhouse",
                display_name="Greenhouse",
                layer="official_ats",
                admin_status="live",
                rollout_stage="live",
                pagination_mode="none",
                supports_incremental_sync=False,
                rate_limit_per_minute=30,
            ),
            _connector(
                key="lever",
                display_name="Lever",
                layer="official_ats",
                admin_status="live",
                rollout_stage="live",
                pagination_mode="none",
                supports_incremental_sync=False,
                rate_limit_per_minute=20,
            ),
            _connector(
                key="ashby",
                display_name="Ashby",
                layer="official_ats",
                admin_status="beta",
                rollout_stage="next",
                pagination_mode="page",
                supports_incremental_sync=True,
                rate_limit_per_minute=20,
            ),
            _connector(
                key="workday",
                display_name="Workday",
                layer="official_ats",
                admin_status="planned",
                rollout_stage="later",
                pagination_mode="page",
                supports_incremental_sync=False,
                rate_limit_per_minute=10,
            ),
            _connector(
                key="smartrecruiters",
                display_name="SmartRecruiters",
                layer="official_ats",
                admin_status="planned",
                rollout_stage="later",
                pagination_mode="page",
                supports_incremental_sync=True,
                rate_limit_per_minute=10,
            ),
            _connector(
                key="icims",
                display_name="iCIMS",
                layer="official_ats",
                admin_status="planned",
                rollout_stage="later",
                pagination_mode="page",
                supports_incremental_sync=True,
                rate_limit_per_minute=10,
            ),
            _connector(
                key="jobvite",
                display_name="Jobvite",
                layer="official_ats",
                admin_status="planned",
                rollout_stage="later",
                pagination_mode="page",
                supports_incremental_sync=True,
                rate_limit_per_minute=10,
            ),
            _connector(
                key="bamboohr",
                display_name="BambooHR",
                layer="official_ats",
                admin_status="planned",
                rollout_stage="later",
                pagination_mode="page",
                supports_incremental_sync=False,
                rate_limit_per_minute=10,
            ),
            _connector(
                key="comeet",
                display_name="Comeet",
                layer="official_ats",
                admin_status="planned",
                rollout_stage="later",
                pagination_mode="page",
                supports_incremental_sync=True,
                rate_limit_per_minute=10,
            ),
            _connector(
                key="successfactors",
                display_name="SuccessFactors",
                layer="official_ats",
                admin_status="planned",
                rollout_stage="later",
                pagination_mode="page",
                supports_incremental_sync=False,
                rate_limit_per_minute=8,
            ),
            _connector(
                key="oracle-recruiting-cloud",
                display_name="Oracle Recruiting Cloud",
                layer="official_ats",
                admin_status="planned",
                rollout_stage="later",
                pagination_mode="page",
                supports_incremental_sync=False,
                rate_limit_per_minute=8,
            ),
            _connector(
                key="company-api",
                display_name="Company Career Sites",
                layer="company_careers",
                admin_status="planned",
                rollout_stage="later",
                pagination_mode="page",
                supports_incremental_sync=True,
                rate_limit_per_minute=10,
            ),
            _connector(
                key="microsoft-careers",
                display_name="Microsoft Careers",
                layer="company_careers",
                admin_status="planned",
                rollout_stage="later",
                pagination_mode="page",
                supports_incremental_sync=True,
                rate_limit_per_minute=12,
            ),
            _connector(
                key="google-careers",
                display_name="Google Careers",
                layer="company_careers",
                admin_status="planned",
                rollout_stage="later",
                pagination_mode="page",
                supports_incremental_sync=True,
                rate_limit_per_minute=12,
            ),
            _connector(
                key="meta-careers",
                display_name="Meta Careers",
                layer="company_careers",
                admin_status="planned",
                rollout_stage="later",
                pagination_mode="page",
                supports_incremental_sync=True,
                rate_limit_per_minute=12,
            ),
            _connector(
                key="amazon-jobs",
                display_name="Amazon Jobs",
                layer="company_careers",
                admin_status="planned",
                rollout_stage="later",
                pagination_mode="page",
                supports_incremental_sync=True,
                rate_limit_per_minute=12,
            ),
            _connector(
                key="apple-careers",
                display_name="Apple Careers",
                layer="company_careers",
                admin_status="planned",
                rollout_stage="later",
                pagination_mode="page",
                supports_incremental_sync=True,
                rate_limit_per_minute=12,
            ),
            _connector(
                key="nvidia-careers",
                display_name="NVIDIA Careers",
                layer="company_careers",
                admin_status="planned",
                rollout_stage="later",
                pagination_mode="page",
                supports_incremental_sync=True,
                rate_limit_per_minute=12,
            ),
            _connector(
                key="tesla-careers",
                display_name="Tesla Careers",
                layer="company_careers",
                admin_status="planned",
                rollout_stage="later",
                pagination_mode="page",
                supports_incremental_sync=True,
                rate_limit_per_minute=12,
            ),
            _connector(
                key="linkedin-jobs",
                display_name="LinkedIn Jobs",
                layer="job_aggregator",
                admin_status="planned",
                rollout_stage="later",
                pagination_mode="page",
                supports_incremental_sync=True,
                rate_limit_per_minute=8,
            ),
            _connector(
                key="indeed",
                display_name="Indeed",
                layer="job_aggregator",
                admin_status="planned",
                rollout_stage="later",
                pagination_mode="page",
                supports_incremental_sync=True,
                rate_limit_per_minute=8,
            ),
            _connector(
                key="ziprecruiter",
                display_name="ZipRecruiter",
                layer="job_aggregator",
                admin_status="planned",
                rollout_stage="later",
                pagination_mode="page",
                supports_incremental_sync=True,
                rate_limit_per_minute=8,
            ),
            _connector(
                key="dice",
                display_name="Dice",
                layer="job_aggregator",
                admin_status="planned",
                rollout_stage="later",
                pagination_mode="page",
                supports_incremental_sync=True,
                rate_limit_per_minute=8,
            ),
            _connector(
                key="wellfound",
                display_name="Wellfound",
                layer="job_aggregator",
                admin_status="planned",
                rollout_stage="later",
                pagination_mode="page",
                supports_incremental_sync=True,
                rate_limit_per_minute=8,
            ),
            _connector(
                key="otta",
                display_name="Otta",
                layer="job_aggregator",
                admin_status="planned",
                rollout_stage="later",
                pagination_mode="page",
                supports_incremental_sync=True,
                rate_limit_per_minute=8,
            ),
            _connector(
                key="yc-jobs",
                display_name="Y Combinator Jobs",
                layer="job_aggregator",
                admin_status="planned",
                rollout_stage="later",
                pagination_mode="page",
                supports_incremental_sync=True,
                rate_limit_per_minute=6,
            ),
            _connector(
                key="builtin",
                display_name="Built In",
                layer="job_aggregator",
                admin_status="planned",
                rollout_stage="later",
                pagination_mode="page",
                supports_incremental_sync=True,
                rate_limit_per_minute=8,
            ),
            _connector(
                key="remoteok",
                display_name="Remote OK",
                layer="job_aggregator",
                admin_status="planned",
                rollout_stage="later",
                pagination_mode="page",
                supports_incremental_sync=True,
                rate_limit_per_minute=6,
            ),
            _connector(
                key="weworkremotely",
                display_name="We Work Remotely",
                layer="job_aggregator",
                admin_status="planned",
                rollout_stage="later",
                pagination_mode="page",
                supports_incremental_sync=True,
                rate_limit_per_minute=6,
            ),
            _connector(
                key="levelsfyi-jobs",
                display_name="Levels.fyi Jobs",
                layer="job_aggregator",
                admin_status="planned",
                rollout_stage="later",
                pagination_mode="page",
                supports_incremental_sync=True,
                rate_limit_per_minute=6,
            ),
            _connector(
                key="hackernews-whos-hiring",
                display_name="Hacker News Who's Hiring",
                layer="job_aggregator",
                admin_status="planned",
                rollout_stage="later",
                pagination_mode="page",
                supports_incremental_sync=False,
                rate_limit_per_minute=4,
            ),
            _connector(
                key="internet-discovery-agent",
                display_name="Internet Discovery Agent",
                layer="discovery_agent",
                admin_status="planned",
                rollout_stage="later",
                pagination_mode="page",
                supports_incremental_sync=True,
                rate_limit_per_minute=4,
            ),
        )
    )
